# Generated by Django 4.2.2 on 2023-06-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandPrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pais', models.CharField(max_length=20)),
                ('win', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('podios', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Escuderias',
            new_name='Escuderia',
        ),
    ]
