# Generated by Django 4.2.2 on 2023-07-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_grandprix_piloto_rename_escuderias_escuderia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grandprix',
            old_name='Pais',
            new_name='pais',
        ),
        migrations.AddField(
            model_name='grandprix',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
