# Generated by Django 4.2.2 on 2023-07-14 06:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_rename_pais_grandprix_pais_grandprix_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grandprix',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
