# Generated by Django 4.2.2 on 2023-07-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_grandprix_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandprix',
            name='autor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='grandprix',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
