# Generated by Django 4.2.2 on 2023-07-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_grandprix_autor_grandprix_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandprix',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
